/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/TZKLZ5AtM6R
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function Pricing() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-background">
      <div className="max-w-3xl px-4 md:px-0">
        <div className="text-center space-y-4 mb-12">
          <h1 className="text-4xl font-bold tracking-tight">Acme SaaS</h1>
          <p className="text-muted-foreground text-lg">
            Unlock the power of our cutting-edge SaaS platform and take your business to new heights.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="bg-card rounded-lg shadow-lg p-6 space-y-4">
            <div>
              <h3 className="text-2xl font-bold">Starter</h3>
              <p className="text-muted-foreground">Perfect for small businesses and individuals.</p>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-4xl font-bold">$9</span>
              <span className="text-muted-foreground">/mo</span>
            </div>
            <Button className="w-full">Get Started</Button>
          </div>
          <div className="bg-card-1 rounded-lg shadow-lg p-6 space-y-4 relative border-2 border-[#e74c3c]">
            <div className="absolute top-0 right-0 bg-[#e74c3c] px-4 py-2 rounded-tl-[0px] rounded-br-[0px] rounded-bl-[10px] rounded-tr-[0px]  font-bold text-primary-foreground">
              Most Popular
            </div>
            <div>
              <h3 className="text-2xl font-bold">Pro</h3>
              <p className="text-muted-foreground">Ideal for growing businesses and teams.</p>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-4xl font-bold">$29</span>
              <span className="text-muted-foreground">/mo</span>
            </div>
            <Button className="w-full">Get Started</Button>
          </div>
          <div className="bg-card rounded-lg shadow-lg p-6 space-y-4">
            <div>
              <h3 className="text-2xl font-bold">Enterprise</h3>
              <p className="text-muted-foreground">Tailored for large organizations and complex needs.</p>
            </div>
            <div className="flex items-baseline gap-2">
              <span className="text-4xl font-bold">$99</span>
              <span className="text-muted-foreground">/mo</span>
            </div>
            <Button className="w-full">Get Started</Button>
          </div>
        </div>
      </div>
    </div>
  )
}
